---
title: "GAMBLR family of packages"
---

GAMBLR.open is the open-source package recommended for the community interested in lymphoma genomics research and are not members of the GAMBL consortium, or if you are waiting for your access approval but want to get started.

The GAMBLR.open family includes:

* [GAMBLR.data](https://github.com/morinlab/GAMBLR.data) - a "storage unit" with [different types](https://morinlab.github.io/GAMBLR.data/resources/bundled_data.html) of bundled data.
* [GAMBLR.helpers](https://github.com/morinlab/GAMBLR.helpers) - a set of low-level functions for data operation.
* [GAMBLR.utils](https://github.com/morinlab/GAMBLR.utils) - higher level set of functions to operate on genomic data.
* [GAMBLR.viz](https://github.com/morinlab/GAMBLR.viz) - set of functions used mostly for visualizations.
* [GAMBLR.predict](https://github.com/morinlab/GAMBLR.predict) - a collection of machine learning algorithms and functions to pre-format inputs for these models. Contains classifiers of [Burkitt](https://doi.org/10.1182/blood.2022016534) and [Follicular](https://doi.org/10.1182/blood.2022018719) lymphomas originally published, as well as reproduced of DLBCL classification by the groupings of [Chapuy et al](https://doi.org/10.1038/s41591-018-0016-8), [Lacy et al](https://doi.org/10.1182/blood.2019003535), and [Runge et al](https://doi.org/10.1111/bjh.17132).
* GAMBLR.open - this package.

This diagram illustrates in a simplified way the dependency relationship of
different packages in the GAMBLR family:

```{mermaid}
%%{
    init : {
        "flowchart" : { "curve" : "monotoneX" },
        'themeVariables': {'fontSize': '24px'}
    }

}%%
flowchart LR
  A("GAMBLR.data") ==> B("GAMBLR.helpers")
  B ==> C("GAMBLR.utils")
  B ==> D("GAMBLR.predict")
  D ==> E("GAMBLR.open")
  C ==> F("GAMBLR.viz")
  F ==> E
  classDef A,B font-size:18pt;
  style E fill:#6aa84f,stroke:#333,stroke-width:4,font-size:20px
```

All dependencies should be installed automatically for you, just like with any other R package. If not, please report the issue in the appropriate GitHub repo.
